<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * townRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class townRepository extends EntityRepository
{
    public function getTownLike($country, $town)
    {
        $town = "%" . $town . "%"; // QUI CONTIENT LE NOM DU VILLAGE/VILLE
        $qb = $this->createQueryBuilder('t')
            ->select('t.town')
            ->where('t.country = :country')
            ->andWhere('t.town LIKE :town')
            ->setParameter('country', $country) // PROTECTION CONTRE LES INJECTIONS SQL
            ->setParameter('town', $town) // PROTECTION CONTRE LES INJECTIONS SQL
            ->getQuery();
        return $qb->getResult();
    }
}
